CI/CD test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+  workflow_dispatch:    # <-- Добавлено для ручного запуска
 
 jobs:
   deploy:
@@ -23,7 +24,7 @@ jobs:
         script: |
           echo "Current directory before cd:"
           pwd
-          cd /home/ruslan/telegramtetrisblitz.ru/app || { echo "Directory not found!"; exit 1; }
+          cd /home/${{ secrets.USER }}/telegramtetrisblitz.ru/app || { echo "Directory not found!"; exit 1; }
           echo "Changed directory to:"
           pwd
           echo "Pulling latest changes..."
@@ -32,4 +33,4 @@ jobs:
           npm install
           echo "Restarting or starting pm2 process..."
           pm2 restart telegram-tetris || pm2 start node_modules/.bin/live-server --name telegram-tetris -- public
-          echo "Deployment finished"
+          echo "Deployment finished."
